### ISSUE TITLE
Install Inspyred offline

### ISSUE THREAD

**Issue by TsingQAQ** [aarongarrett/inspyred#10]
* inspyred version: latest
* Python version: python 3.5 (Anaconda Edition)
* Operating System: Win 10

### Description

Hi there,
I get a PC with no network connection.
I'm trying to install Inspyred offline.

### What I Did

I've seen that there's a setup.py in the file.
I'm using the `python setup.py install` to run this and it seems that no problem occurs
However, when I'm tring:
`from inspyred import ec`
An import Error occurs indicating that no module names ec exists.
So I'd like to know if there are some way to install this package offline.

Thanks in advance

**Comment by aarongarrett** [comment]
I'm sorry about the delay. I didn't see this issue until now.
I don't use Anaconda, so I'm not entirely sure. Did you resolve the problem, or did you give up because I abandoned you? :-)

**Comment by TsingQAQ** [comment]
lol, that's totally fine so seems google group may be a better community for this code.

Nope, but I think its not a problem of Anaconda, since its just a distribution which contains a standard python and some other hot packages, I would expect that using a standalone python and   `python setup.py install` will also encounter this problem, though I've not tried in that situation.

As for me, I just move to a net available PC, but if this is a problem, some fixes are expected~

**Comment by sanjayankur31** [comment]
One should now be able to install inspyred locally from sources using `pip install .`. I'll close this, but please re-open if it doesn't work for you.
