### ISSUE TITLE
NSGA2 minimizaton fits only the first fitness value in the multiobjective optimization problem

### ISSUE THREAD

**Issue by rat-h** [aarongarrett/inspyred#19]
* inspyred version: 1.0.1 (latest)
* Python version: 3.7.3 (default, Oct  7 2019, 12:56:13) 
* Operating System: Ubuntu based, Pop-OS!

### Description
I'm trying to follow this paper [Optimizing computer models of corticospinal neurons to replicate in vitro dynamics](https://www.physiology.org/doi/full/10.1152/jn.00570.2016) and employ NSGA2 for parameter fitting of neurons.

I found that NSGA2 optimizes only the first fitness value in the multiobjective optimization problem. 

I think, there is a problem in inspyred/ec/replacers, function: `nsga_replacement` line 350:
```
combined[p] < combined[q]
```
which leads to inspyred/ec/ec class Individual, operator  `__lt__`, where two fitness lists are comparing (lines 335 and 337)
```
return self.fitness < other.fitness
```

A simple test shows that python compares only the first element of the list and, seems, ignores others:
```
>>> [11.1 , 0. , 0.]<[ 11.0 , 3393.63 , 3411.87 ] 
False
```
For non-dominant minimization, fitness function on the left of < is the dominant solution, but compassing makes it non-dominant.

**Comment by aarongarrett** [comment]
If you use a multiobjective method, you have to wrap your fitness in a Pareto object in the evaluator, as described in the documentation. The Pareto class overloads less-than to provide a dominance operator.
