### ISSUE TITLE
RTD docs are missing

### ISSUE THREAD

**Issue by sanjayankur31** [aarongarrett/inspyred#23]
Hi there,

I was looking for the inpyred docs on RTD and can't seem to find them there. The link in the badge also returns a 404.

Could the link to the docs be corrected please?

Cheers,

**Comment by sanjayankur31** [comment]
PS: the docs build fine locally with sphinx-build 4.1.2 here

**Comment by sanjayankur31** [comment]
I've manually added the project to RTD and invited you @aarongarrett .

https://readthedocs.org/dashboard/inspyred/

We need to set up the GitHub hooks for this to work properly too. Alternatively, I could delete this manually set up project and if you sign in and import it from the list it shows you on your account, I think it'll automatically set up the webhook etc.

**Comment by aarongarrett** [comment]
If you delete the one you have, I'll try the import.

--
Aaron Garrett

**Comment by sanjayankur31** [comment]
Cool, deleted now.

**Comment by aarongarrett** [comment]
OK. It's imported but failing to build because of a sphinx issue, it looks
like.

--
Aaron Garrett

**Comment by sanjayankur31** [comment]
No worries, if you can add me to readthedocs too, I can fix that. The docs did seem to build correctly locally, so it must be something small that I've missed :crossed_fingers:

**Comment by sanjayankur31** [comment]
Fixed: https://inspyred.readthedocs.io/en/latest/

I've also enabled rtd to build on every commit and PRs etc.  

Closing this now.
