### ISSUE TITLE
Release of new version on pypi

### ISSUE THREAD

**Issue by gedeck** [aarongarrett/inspyred#25]
* inspyred version: 1.0.1
* Python version: 3.10
* Operating System: NA

### Description

You already fixed the problem with the Iterable import in this repository. With Python 3.10, version 1.0.1 can no longer be used. When do you plan to release a new version on pypi?

### What I Did
Third party package (pykriging) that uses inspyred fails to work when using with Python 3.10

**Comment by jchen6727** [comment]
(dev) XXXX@XXXX:~$ conda list | grep inspyred
inspyred                  1.0.1                    pypi_0    pypi


  File "/home/XXX/miniconda3/envs/dev/lib/python3.10/site-packages/inspyred/ec/ec.py", line 115, in __init__
    if not isinstance(self.lower_bound, collections.Iterable):
AttributeError: module 'collections' has no attribute 'Iterable'


Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import collections
>>> collections.Iterable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'collections' has no attribute 'Iterable'
>>> collections.abc.Iterable
<class 'collections.abc.Iterable'>

**Comment by sanjayankur31** [comment]
I've released 1.0.2 with a bunch of fixes, please do test it out and file new issues if you encounter them

https://pypi.org/project/inspyred/1.0.2/
