### ISSUE TITLE
No collection.Sequence in Python 3.11

### ISSUE THREAD

**Issue by ThePseudo** [aarongarrett/inspyred#26]
* inspyred version: 1.0.1
* Python version: 3.11
* Operating System: MacOS

### Description

Inspyred wants the generator to generate a ```collection.Sequence```, which does not exist in Python > 3.9

Update: neither is collections.Iterable.

### What I Did

On ec.py, commented lines 422, 423 and 424

Edit:
on a better note, just import collections.abc and replace ```collections.*``` with ```collections.abc.*```

**Comment by sanjayankur31** [comment]
#24 should fix these, I think.

**Comment by sanjayankur31** [comment]
(these are already fixed in master, actually). #24 adds tweaks to make it also work on py2 which won't be required if inspyred drops py2 support.

**Comment by sanjayankur31** [comment]
I've released 1.0.2 with a bunch of fixes, please do test it out and file new issues if you encounter them

https://pypi.org/project/inspyred/1.0.2/
